name: 测试构建

on:
  # 手动触发
  workflow_dispatch:
  
  # Pull Request 时触发
  pull_request:
    branches: [ master ]
    paths:
      - 'source/**'
      - 'main.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'build.py'
      - 'xhs_downloader.spec'

jobs:
  test-build:
    name: 快速测试构建
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller>=6.0.0

    - name: 测试构建
      run: |
        python -c "
        import sys
        print(f'Python版本: {sys.version}')
        print(f'平台: {sys.platform}')
        
        # 测试导入主要模块
        try:
            from source import Settings, XHS, XHSDownloader
            print('✅ 主要模块导入成功')
        except Exception as e:
            print(f'❌ 模块导入失败: {e}')
            sys.exit(1)
        
        # 测试依赖
        import aiofiles, aiosqlite, httpx, lxml, textual
        print('✅ 依赖检查通过')
        "

    - name: 验证 spec 文件
      run: |
        python -c "
        import PyInstaller.utils.hooks
        spec_file = 'xhs_downloader.spec'
        with open(spec_file, 'r', encoding='utf-8') as f:
            content = f.read()
        print(f'✅ Spec文件读取成功: {len(content)} 字符')
        "

    - name: 快速构建测试 (仅验证无错误)
      run: |
        pyinstaller --clean --noconfirm xhs_downloader.spec

    - name: 验证构建结果
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          EXECUTABLE="dist/XHS-Downloader.exe"
        else
          EXECUTABLE="dist/XHS-Downloader"
        fi
        
        if [ -f "$EXECUTABLE" ]; then
          echo "✅ 构建成功: $EXECUTABLE"
          ls -la dist/
        else
          echo "❌ 构建失败: 未找到 $EXECUTABLE"
          ls -la dist/ || echo "dist目录不存在"
          exit 1
        fi